### ISSUE TITLE
dragnheadtilt shows up weirdly if Calibri font isn't installed

### ISSUE THREAD

**Issue by HastagGuigui** [chr-1x/dragn-emoji#3]
This whole emoji set is pretty cool! unfortunately, using \<text> svgs is very risqué
![image](https://github.com/chr-1x/dragn-emoji/assets/47950669/4bc145e3-0638-488e-a597-2633087c8171)

**Comment by ZMYaro** [comment]
@HastagGuigui What do you even mean by that?  SVGs are easily the standard format for graphics like these.

**Comment by HastagGuigui** [comment]
Oh it badly formatted, I meant `<text>` svg tags!

**Comment by ZMYaro** [comment]
Oh, I see what you mean!  Yes, using `<text>` is risky (if not _risqué_ 😄), and it would probably be good to have a version that bakes that to a path.

**Comment by chr-1x** [comment]
Closed by #4, thanks @ZMYaro

**Comment by ZMYaro** [comment]
You're welcome; glad I could help!
